config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    @flat.save
    redirect_to flat_path(@flat)
  end

  def edit
    @flat = Flat.find(params[:id])
  end

  def update
    @flat = Flat.find(params[:id])
    @flat.update(flat_params)
    @flat.save
    redirect_to flat_path(@flat)
  end

  def destroy
    @flat = Flat.find(params[:id])
    @flat.destroy
    @flat.save
    redirect_to flats_path
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/edit.html.erb
<h1>Edit your flat</h1>

<%= simple_form_for [@flat] do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :description %>
  <%= f.input :number_of_guests %>
  <%= f.input :price_per_night %>
  <%= f.submit "Add", class: "btn" %>
<% end %>

app/views/flats/index.html.erb
<h1>All our flats (<%= @flats.count %>)</h1>

<div class="card-container">
  <% @flats.each do |flat| %>
    <div class="flat-card " >
      <h3><%= flat.name %></h3>
      <p><em><%= flat.address %></em></p>
      <p><%= flat.number_of_guests %> people</p>
      <p><%= flat.price_per_night %> €</p>
      <div class="card-footer">
        <%= link_to 'Details', flat_path(flat.id) %>
        <%= link_to 'Edit', edit_flat_path(flat.id) %>
        <%= link_to 'Remove', flat_path(flat.id), method: :delete %>
      </div>
    </div>
  <% end %>
</div>

app/views/flats/new.html.erb
<h1>Add your flat</h1>

<%= simple_form_for [@flat] do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :description %>
  <%= f.input :number_of_guests %>
  <%= f.input :price_per_night %>
  <%= f.submit "Add", class: "btn" %>
<% end %>

app/views/flats/show.html.erb
<h1><%= @flat.name %></h1>

<img src="https://picsum.photos/500/300/?random" alt="">

<h3><%= @flat.address %></h3>
<h3>We can host up to <%= @flat.number_of_guests %> guests</h3>
<h3>It only costs <%= @flat.price_per_night %> €</h3>
<br>
<%= link_to flats_path do %>
  <button class="btn">Back</button>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="my-container">
      <div class="my-navbar">
        <a href="http://localhost:3000/flats" class="my-navbar-item my-navbar-link">Simple Airbnb</a>
        <a href="http://localhost:3000/flats/new" class="my-navbar-item my-navbar-link">Add a flat</a>
      </div>
    </div>
    <br><br><br>
    <div class="yield">
      <%= yield %>
    </div>
  </body>
</html>